### ISSUE TITLE
Cloning into "SpatialOps" fails

### ISSUE THREAD

**Issue by pf4d** [cchriste/uintah#1]
Hello,

I've recently decided to use your software to learn the GIMP Method and using your configure script to install Uintah on Ubuntu 16.04, I follow this procedure :

``
sudo apt-get install subversion libhypre-dev petsc-dev libxml2-dev zlib1g-dev liblapack-dev cmake libglew-dev libxmu-dev g++ gfortran libboost-all-dev git libxrender-dev libxi-dev
``

then

``
../src/configure --enable-debug --enable-all-components --with-boost=/usr --enable-wasatch_3p F77=gfortran
``

As suggested in your documentation.  It appears that the git repos have moved (to gitlab?) but the configure script attempts to clone from an old, currently non-existant repository : 

```
------------------------------------------------------------------
Building Wasatch Thirdparty Libraries...

  Using Boost: Built In

  Using Cmake: /usr/bin/cmake
------------------------------------------------------------------

cd /home/pf4d/software/uintah/dbg/Wasatch3P
mkdir -p src
mkdir -p install
rm -rf install/*
cd src
rm -rf SpatialOps
env GIT_SSL_NO_VERIFY=true git clone --depth 1 https://software.crsim.utah.edu:8443/James_Research_Group/SpatialOps.git SpatialOps
Cloning into 'SpatialOps'...
fatal: unable to access 'https://software.crsim.utah.edu:8443/James_Research_Group/SpatialOps.git/': Failed to connect to software.crsim.utah.edu port 8443: Connection timed out

An error occurred in the buid_wasatch script:

  The error was from this line: env GIT_SSL_NO_VERIFY=true git clone --depth 1 https://software.crsim.utah.edu:8443/James_Research_Group/SpatialOps.git SpatialOps

configure: error: Failed to build Wasatch 3p libraries...
```

This leads me to believe there may be a current or development Uintah repository to clone from that includes the correct repo pointers.  Is it possible for me to have access to this repository?

Thanks,
Evan Cummings

**EDIT** :

On closer look, it appears that the links in ``build_wasatch_3p.sh`` point to the same repository described by https://software.crsim.utah.edu/migrating-to-gitlab/, but I am simply not able to access the repository.  Is there a registration or something I need to do to receive access?

**Comment by cchriste** [comment]
Hi Evan,

You should email Martin Berzens, berzens@sci.utah.edu, for permission to access the project. My clone is very out-of-date and in fact I'll probably delete it now since I don't develop this project from here any longer.

Regards,
Cameron
